
import React, { useState } from 'react';
import { Case, Client } from '../types';
import { Icons } from '../constants';
import { getLegalAdvice } from '../services/geminiService';
import Modal from './Modal';
import { jsPDF } from 'jspdf';

interface CaseDetailProps {
  caseData: Case;
  clientData?: Client; // Injected linked client
  onEdit: (caseData: Case) => void;
  onDelete: (id: string) => void;
  onBack: () => void;
  onViewHistory: () => void;
}

const CaseDetail: React.FC<CaseDetailProps> = ({ caseData, clientData, onEdit, onDelete, onBack, onViewHistory }) => {
  const [aiInsights, setAiInsights] = useState<string | null>(null);
  const [loadingAi, setLoadingAi] = useState(false);
  const [showConfirmDelete, setShowConfirmDelete] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const fetchAiInsights = async () => {
    setLoadingAi(true);
    const advice = await getLegalAdvice(caseData.caseType, caseData.stepOfTheDay, caseData.notes);
    setAiInsights(advice || "No specific insights available.");
    setLoadingAi(false);
  };

  const generatePdf = async () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = 20;

    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text('Adv Dairy - Case Report', margin, y);
    
    y += 10;
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.line(margin, y, 210 - margin, y);
    y += 15;

    // Case Information Section
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text('CASE IDENTIFICATION', margin, y);
    y += 8;

    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(`Case No: ${caseData.caseNumber}`, margin, y);
    y += 8;

    if (caseData.caseNameParties) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(caseData.caseNameParties, margin, y);
      y += 7;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`${caseData.courtName} | ${caseData.caseType}`, margin, y);
    y += 15;

    // Listing Grid (Manual)
    doc.setDrawColor(241, 245, 249); // slate-100
    doc.setFillColor(248, 250, 252); // slate-50
    doc.rect(margin, y, 170, 35, 'F');
    
    let gridY = y + 8;
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text('SERIAL NO.', margin + 5, gridY);
    doc.text('NEXT DATE', margin + 45, gridY);
    doc.text('PREVIOUS DATE', margin + 85, gridY);
    doc.text('STEP OF DAY', margin + 125, gridY);
    
    gridY += 7;
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.text(caseData.serialNumber || '-', margin + 5, gridY);
    doc.setTextColor(217, 119, 6); // amber-600
    doc.text(new Date(caseData.nextDate).toLocaleDateString('en-GB'), margin + 45, gridY);
    doc.setTextColor(15, 23, 42);
    doc.text(caseData.previousDate ? new Date(caseData.previousDate).toLocaleDateString('en-GB') : 'N/A', margin + 85, gridY);
    doc.text(caseData.stepOfTheDay, margin + 125, gridY);
    
    y += 45;

    // Client Info
    if (clientData) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139);
      doc.text('REPRESENTING CLIENT', margin, y);
      y += 8;

      doc.setFontSize(14);
      doc.setTextColor(15, 23, 42);
      doc.text(clientData.name, margin, y);
      y += 6;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Contact: ${clientData.phone} | Email: ${clientData.email || 'N/A'}`, margin, y);
      y += 15;
    }

    // Legal Section
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text('SECTION AND ACT', margin, y);
    y += 8;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(15, 23, 42);
    doc.text(caseData.section || 'Not specified', margin, y);
    y += 15;

    // Notes
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text('CASE NOTES', margin, y);
    y += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85); // slate-700
    
    const splitNotes = doc.splitTextToSize(caseData.notes || 'No notes available.', 170);
    doc.text(splitNotes, margin, y);
    
    // Footer
    const pageCount = doc.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`Generated by Adv Dairy on ${new Date().toLocaleString()} - Page ${i} of ${pageCount}`, margin, 285);
    }

    return doc;
  };

  const handlePrintPdf = async () => {
    setIsGeneratingPdf(true);
    try {
      const doc = await generatePdf();
      doc.save(`${caseData.caseNumber.replace(/[/\\?%*:|"<>]/g, '-')}_File.pdf`);
    } catch (err) {
      console.error("PDF Error:", err);
      alert("Failed to generate PDF for printing.");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleSharePdf = async () => {
    setIsGeneratingPdf(true);
    try {
      const doc = await generatePdf();
      const pdfBlob = doc.output('blob');
      const filename = `Case_${caseData.caseNumber.replace(/[/\\?%*:|"<>]/g, '-')}.pdf`;
      const file = new File([pdfBlob], filename, { type: 'application/pdf' });

      if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: `Case File: ${caseData.caseNumber}`,
          text: `Legal document for Case No. ${caseData.caseNumber} shared via Adv Dairy.`,
        });
      } else {
        // Fallback: Download and notify
        doc.save(filename);
        alert("PDF generated and downloaded. You can now share it manually.");
      }
    } catch (err) {
      console.error("Share Error:", err);
      alert("Failed to share as PDF.");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto pb-12">
      <button onClick={onBack} className="no-print flex items-center gap-2 text-slate-500 hover:text-slate-900 font-medium transition-colors">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 18-6-6 6-6"/></svg>
        Back to Diary
      </button>

      <div className="flex flex-col md:flex-row justify-between items-start gap-4">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <span className="bg-amber-100 text-amber-700 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest">
              {caseData.caseType}
            </span>
            <span className="text-slate-400 font-mono text-sm">#{caseData.caseId}</span>
          </div>
          <h2 className="text-4xl font-serif text-slate-900 leading-tight">{caseData.caseNumber}</h2>
          {caseData.caseNameParties && (
            <p className="text-xl font-bold text-slate-800 mt-1">{caseData.caseNameParties}</p>
          )}
          <p className="text-xl text-slate-500 font-medium">{caseData.courtName}</p>
        </div>

        <div className="flex flex-wrap gap-2 w-full md:w-auto no-print">
          <button 
            disabled={isGeneratingPdf}
            onClick={handlePrintPdf}
            title="Download as PDF"
            className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-3 bg-white border border-slate-200 text-slate-700 font-bold rounded-xl hover:bg-slate-50 transition-all shadow-sm disabled:opacity-50"
          >
            {isGeneratingPdf ? <div className="w-4 h-4 border-2 border-slate-300 border-t-slate-600 rounded-full animate-spin" /> : <Icons.Print />}
            <span className="hidden lg:inline">{isGeneratingPdf ? 'Processing...' : 'PDF'}</span>
          </button>
          <button 
            disabled={isGeneratingPdf}
            onClick={handleSharePdf}
            title="Share as PDF"
            className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-3 bg-white border border-slate-200 text-slate-700 font-bold rounded-xl hover:bg-slate-50 transition-all shadow-sm disabled:opacity-50"
          >
            {isGeneratingPdf ? <div className="w-4 h-4 border-2 border-slate-300 border-t-slate-600 rounded-full animate-spin" /> : <Icons.Share />}
            <span className="hidden lg:inline">{isGeneratingPdf ? 'Wait...' : 'Share PDF'}</span>
          </button>
          <button 
            onClick={() => onEdit(caseData)}
            className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-3 bg-slate-900 text-white font-bold rounded-xl hover:bg-slate-800 transition-all shadow-sm"
          >
            <Icons.Edit />
            Edit
          </button>
          <button 
            onClick={() => setShowConfirmDelete(true)}
            className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-3 bg-red-50 text-red-600 font-bold rounded-xl hover:bg-red-100 transition-all shadow-sm"
          >
            <Icons.Trash />
            Delete
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 space-y-6">
          {/* Linked Client Card */}
          {clientData && (
            <div className="bg-slate-900 text-white rounded-[2rem] p-6 shadow-xl flex items-center gap-6 group print:bg-white print:text-black print:border print:border-slate-200 print:shadow-none">
              <div className="flex-shrink-0 print:hidden">
                {clientData.photo ? (
                  <img src={clientData.photo} alt={clientData.name} className="w-16 h-16 rounded-2xl object-cover border-2 border-slate-700" />
                ) : (
                  <div className="w-16 h-16 bg-slate-800 rounded-2xl flex items-center justify-center text-slate-500">
                    <Icons.User />
                  </div>
                )}
              </div>
              <div className="min-w-0">
                <p className="text-[10px] font-bold text-amber-500 uppercase tracking-widest mb-1 print:text-amber-700">Representing Client</p>
                <h4 className="text-xl font-bold truncate">{clientData.name}</h4>
                <div className="flex gap-4 mt-1">
                   <p className="text-xs text-slate-400 flex items-center gap-1 print:text-slate-600">
                     <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"></path></svg>
                     {clientData.phone}
                   </p>
                   <p className="text-xs text-slate-400 flex items-center gap-1 truncate print:text-slate-600">
                     <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path></svg>
                     {clientData.email}
                   </p>
                </div>
              </div>
            </div>
          )}

          <div className="bg-white border border-slate-200 rounded-3xl p-8 shadow-sm print:border-none print:p-0">
            <div className="flex justify-between items-center mb-6 no-print">
              <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                <Icons.Calendar />
                Listing Details
              </h3>
              <button 
                onClick={onViewHistory}
                className="text-amber-600 text-sm font-bold hover:text-amber-700 underline underline-offset-4"
              >
                View Procedural History
              </button>
            </div>
            
            <div className="grid grid-cols-2 gap-8">
              <div>
                <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">Serial Number</p>
                <p className="text-2xl font-serif text-black">{caseData.serialNumber}</p>
              </div>
              <div>
                <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">Next Date</p>
                <p className="text-2xl font-serif text-amber-600">{new Date(caseData.nextDate).toLocaleDateString('en-GB')}</p>
              </div>
              <div>
                <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">Previous Date</p>
                <p className="text-lg text-black">{caseData.previousDate ? new Date(caseData.previousDate).toLocaleDateString('en-GB') : 'N/A'}</p>
              </div>
              <div>
                <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">Step of Day</p>
                <p className="text-lg font-bold text-black">{caseData.stepOfTheDay}</p>
              </div>
            </div>

            <div className="mt-8 pt-8 border-t border-slate-100 print:mt-4 print:pt-4">
              <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-2">Section and Act</p>
              <p className="text-black bg-slate-50 p-4 rounded-xl font-medium border border-slate-100 print:bg-white print:border-none print:p-0">{caseData.section}</p>
            </div>
          </div>

          <div className="bg-white border border-slate-200 rounded-3xl p-8 shadow-sm print:border-none print:p-0">
            <h3 className="text-lg font-bold text-slate-900 mb-4 print:text-sm print:mb-2">Case Notes</h3>
            <p className="text-black whitespace-pre-wrap leading-relaxed">
              {caseData.notes || 'No notes added for this case.'}
            </p>
          </div>
        </div>

        <div className="space-y-6">
          <div className="bg-slate-900 text-white rounded-3xl p-6 shadow-xl relative overflow-hidden print:hidden">
            <div className="absolute -right-4 -top-4 opacity-20 transform rotate-12">
              <Icons.Gavel />
            </div>
            
            <h3 className="text-xl font-serif mb-4 flex items-center gap-2">
              <Icons.Sparkles />
              AI Assistant
            </h3>
            
            {aiInsights ? (
              <div className="prose prose-invert prose-sm">
                <p className="text-slate-300 leading-relaxed italic">{aiInsights}</p>
                <button 
                   onClick={() => setAiInsights(null)}
                   className="mt-4 text-amber-400 text-xs font-bold hover:underline"
                >
                  Regenerate
                </button>
              </div>
            ) : (
              <div className="space-y-4">
                <p className="text-sm text-slate-400">Get preparation bullet points and procedural suggestions for this case step.</p>
                <button 
                  onClick={fetchAiInsights}
                  disabled={loadingAi}
                  className="w-full py-3 bg-amber-500 text-slate-900 font-bold rounded-xl hover:bg-amber-400 transition-colors disabled:opacity-50"
                >
                  {loadingAi ? 'Thinking...' : 'Get AI Prep Plan'}
                </button>
              </div>
            )}
          </div>

          <div className="bg-amber-50 border border-amber-100 rounded-3xl p-6 print:border-slate-200 print:bg-white">
            <h3 className="font-bold text-amber-900 mb-2 print:text-amber-700">Daily Reminder</h3>
            <p className="text-sm text-amber-800 print:text-black">Ensure you have your files ready for the <b>{caseData.stepOfTheDay}</b> in <b>{caseData.courtName}</b>.</p>
          </div>
        </div>
      </div>

      <Modal 
        isOpen={showConfirmDelete}
        title="Permanently Delete?"
        message={`This will remove all records for Case No. ${caseData.caseNumber}. This action cannot be undone.`}
        confirmLabel="Yes, Delete Case"
        cancelLabel="Keep Record"
        type="danger"
        onConfirm={() => onDelete(caseData.caseId)}
        onClose={() => setShowConfirmDelete(false)}
      />
    </div>
  );
};

export default CaseDetail;
